### PR TITLE
Updating with correct information

### PR DESCRIPTION
**Pull request by brdilaur-ms**
We are trying to un-depricate this tool. Updating with current information. Please reach out to the sensors team (sensors@microsoft.com) for questions/concerns.

### CODE REVIEW

**Comment by tedhudek** [comment]
Hi @brdilaur-ms I started processing your PR but just saw some more come in.  Let me know when you're ready and I'll evaluate then.  Thanks for the suggestions!

**Comment by brdilaur-ms** [comment]
Sounds good Ted. They should all be done in the next hour or so.
-Bryan

**Comment by tedhudek** [comment]
Thanks Bryan.  Note that you can add to an already open PR if you like.

**Comment by brdilaur-ms** [comment]
Shoot! Sorry about that! I didn’t know. At this point I have updated everything on my end, so you should be good to go. If you have any questions, please contact sensors@microsoft.com.

**Comment by tedhudek** [comment]
No worries Bryan, thanks again for the contributions, we're delighted to have them.  The updates should be live on the Docs.microsoft.com site in a couple minutes.

**Pull request merged**
